sudo: required
language: cpp

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
#        - os: osx
#          osx_image: xcode8.1
#        - os: centos

services:
  - docker

script:
  - docker run -it -v $(pwd):/openbmp centos:centos7 /bin/sh -c "cd openbmp && `cat install_build_run_test_ci.sh`"
