language: cpp

matrix:
    include:
#        - os: linux
#          dist: trusty
#          sudo: required
#        - os: osx
#          osx_image: xcode8.1
        - os: centos/7

script:
  - git clone https://github.com/edenhill/librdkafka.git
  - cd librdkafka
  - ./configure
  - make
  - sudo make install
  - cd ..

  - git clone https://github.com/jbeder/yaml-cpp.git
  - cd yaml-cpp
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=OFF ..
  - make
  - sudo make install

  - mkdir -p build;
  - cmake ./
  - make ./
